version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: django
    command: gunicorn webapp.wsgi:application -b 0.0.0.0:8000
    expose:
      - 8000
    env_file:
      - env_var/.env.app
    depends_on:
      - postgres
      - redis
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx
    depends_on:
      - web
    ports:
      - "8000:80"
  postgres:
    image: postgres:13.0-alpine
    container_name: postgres
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin_pass
      - POSTGRES_DB=prod_db
  redis:
    image: redis:alpine
    container_name: redis
