version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: django
    volumes:
      - type: volume
        source: static_volume
        target: /usr/src/app/static
      - type: volume
        source: media_volume
        target: /usr/src/app/blog/media
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    env_file:
      - code/env_var/.env.dev
    depends_on:
      - postgres
      - redis
  postgres:
    image: postgres:13.0-alpine
    container_name: postgres
    volumes:
      - type: volume
        source: postgres_dev_data
        target: /var/lib/postgresql/data
    env_file:
      - code/env_var/.env.dev.db
  redis:
    image: redis:alpine
    container_name: redis
    volumes:
      - type: volume
        source: redis_dev_data
        target: /data
volumes:
  postgres_dev_data:
  redis_dev_data:
  static_volume:
  media_volume:
