version: '3.3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: ch_prod
    volumes:
      - type: volume
        source: static_volume
        target: /usr/src/app/static
      - type: volume
        source: media_volume
        target: /usr/src/app/media
    command: gunicorn career.wsgi:application -b 0.0.0.0:8000
    expose:
      - 8000
    env_file:
      - code/env_var/.env.prod
    depends_on:
      - postgres

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: ch_nginx_prod
    volumes:
      - type: volume
        source: static_volume
        target: /usr/src/app/static
      - type: volume
        source: media_volume
        target: /usr/src/app/media
    depends_on:
      - web
    ports:
      - "88:80"

  postgres:
    image: postgres:13.0-alpine
    container_name: ch_postgres_prod
    volumes:
      - type: volume
        source: postgres_data
        target: /var/lib/postgresql/data/
    env_file:
      - code/env_var/.env.prod.db

volumes:
  postgres_data:
  static_volume:
  media_volume: