version: '3.3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: django_prod
    volumes:
      - type: volume
        source: static_volume
        target: /usr/src/app/static
      - type: volume
        source: media_volume
        target: /usr/src/app/blog/media
    command: gunicorn memes.wsgi:application -b 0.0.0.0:8000
    expose:
      - 8000
    env_file:
      - code/env_var/.env.prod
    depends_on:
      - postgres
      - redis
      - elasticsearch
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx_prod
    volumes:
      - type: volume
        source: static_volume
        target: /usr/src/app/static
      - type: volume
        source: media_volume
        target: /usr/src/app/blog/media
    depends_on:
      - web
    ports:
      - "88:80"
  postgres:
    image: postgres:13.0-alpine
    container_name: postgres_prod
    volumes:
      - type: volume
        source: postgres_data
        target: /var/lib/postgresql/data/
    env_file:
      - code/env_var/.env.prod.db
  redis:
    image: redis:alpine
    container_name: redis_prod
    volumes:
      - type: volume
        source: redis_data
        target: /data
  elasticsearch:
    image: elasticsearch:5.6.16-alpine
    container_name: search_dev
    volumes:
      - type: volume
        source: elasticsearch_data
        target: /usr/share/elasticsearch/data
    ports:
      - "9200:9200"

volumes:
  elasticsearch_data:
  postgres_data:
  redis_data:
  static_volume:
  media_volume: