version: '3.3'

services:
  backend:
    build:
      context: .
      dockerfile: backend/dockerfile/application
    container_name: ch_django_app
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    env_file:
      - code/backend/env_var/.env.app

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: ch_node_app
    command: npm start
    ports:
      - "80:3000"
    depends_on:
      - backend