version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: django
    volumes:
      - type: volume
        source: static_volume
        target: /usr/src/app/static
      - type: volume
        source: media_volume
        target: /usr/src/app/blog/media
    command: gunicorn memes.wsgi:application -b 0.0.0.0:8000
    expose:
      - 8000
    env_file:
      - code/env_var/.env.prod
    depends_on:
      - postgres
      - redis
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx
    volumes:
      - type: volume
        source: static_volume
        target: /usr/src/app/static
      - type: volume
        source: media_volume
        target: /usr/src/app/blog/media
    depends_on:
      - web
    ports:
      - "8000:80"
  postgres:
    image: postgres:13.0-alpine
    container_name: postgres
    volumes:
      - type: volume
        source: postgres_prod_data
        target: /var/lib/postgresql/data/
    env_file:
      - code/env_var/.env.prod.db
  redis:
    image: redis:alpine
    container_name: redis
    volumes:
      - type: volume
        source: redis_prod_data
        target: /data
volumes:
  postgres_prod_data:
  redis_prod_data:
  static_volume:
  media_volume:
