version: '3.3'

services:
  backend:
    build:
      context: .
      dockerfile: backend/dockerfile/development
    container_name: ch_django_dev
    volumes:
      - type: volume
        source: media_volume
        target: /usr/src/app/media
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    env_file:
      - code/backend/env_var/.env.dev
    depends_on:
      - postgres

  postgres:
    image: postgres:13.0-alpine
    container_name: ch_postgres_dev
    volumes:
      - type: volume
        source: postgres_data
        target: /var/lib/postgresql/data
    env_file:
      - code/backend/env_var/.env.dev.db

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: ch_node_dev
    command: npm start
    ports:
      - "80:3000"
    depends_on:
      - backend

volumes:
  postgres_data:
  media_volume: