version: '3.3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: django_dev
    volumes:
      - type: volume
        source: media_volume
        target: /usr/src/app/blog/media
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    env_file:
      - code/env_var/.env.dev
    depends_on:
      - postgres
      - redis
      - elasticsearch
  postgres:
    image: postgres:13.0-alpine
    container_name: postgres_dev
    volumes:
      - type: volume
        source: postgres_data
        target: /var/lib/postgresql/data
    env_file:
      - code/env_var/.env.dev.db
  redis:
    image: redis:6.2.6-alpine
    container_name: redis_dev
    volumes:
      - type: volume
        source: redis_data
        target: /data
  elasticsearch:
    image: elasticsearch:5.6.16-alpine
    container_name: search_dev
    volumes:
      - type: volume
        source: elasticsearch_data
        target: /usr/share/elasticsearch/data
    ports:
      - "9200:9200"

volumes:
  elasticsearch_data:
  postgres_data:
  redis_data:
  media_volume: