version: '3.3'

services:
  backend:
    build:
      context: .
      dockerfile: backend/dockerfile/production
    container_name: ch_django_prod
    volumes:
      - type: volume
        source: static_volume
        target: /usr/src/app/django_static
      - type: volume
        source: media_volume
        target: /usr/src/app/django_media
    command: gunicorn career.wsgi:application -b 0.0.0.0:8000
    expose:
      - 8000
    env_file:
      - code/backend/env_var/.env.prod
    depends_on:
      - postgres

  nginx:
    build:
      context: .
      dockerfile: nginx/dockerfiles/production
    container_name: ch_nginx_prod
    volumes:
      - type: volume
        source: static_volume
        target: /usr/src/app/django_static
      - type: volume
        source: media_volume
        target: /usr/src/app/django_media
      - type: volume
        source: node_volume
        target: /usr/src/app/build
    depends_on:
      - backend
      - frontend
    ports:
      - "8004:80"

  postgres:
    image: postgres:13.0-alpine
    container_name: ch_postgres_prod
    volumes:
      - type: volume
        source: postgres_data
        target: /var/lib/postgresql/data/
    env_file:
      - code/backend/env_var/.env.prod.db

  frontend:
    build:
      context: .
      dockerfile: frontend/dockerfile/production
    container_name: ch_node_prod
    volumes:
      - type: volume
        source: node_volume
        target: /usr/src/app/build
    depends_on:
      - backend

volumes:
  postgres_data:
  static_volume:
  media_volume:
  node_volume: