version: '3.3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: django_prod
    volumes:
      - type: volume
        source: static_volume
        target: /usr/src/app/static
      - type: volume
        source: media_volume
        target: /usr/src/app/blog/media
    command: gunicorn memes.wsgi:application -b 0.0.0.0:8000
    expose:
      - 8000
    env_file:
      - code/env_var/.env.prod
    depends_on:
      - postgres
      - redis
      - es

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx_prod
    volumes:
      - type: volume
        source: static_volume
        target: /usr/src/app/static
      - type: volume
        source: media_volume
        target: /usr/src/app/blog/media
    depends_on:
      - web
    ports:
      - "8001:80"

  postgres:
    image: postgres:13.0-alpine
    container_name: postgres_prod
    volumes:
      - type: volume
        source: postgres_data
        target: /var/lib/postgresql/data/
    env_file:
      - code/env_var/.env.prod.db

  redis:
    image: redis:alpine
    container_name: redis_prod
    volumes:
      - type: volume
        source: redis_data
        target: /data

  es:
    image: elasticsearch:7.8.1
    container_name: es_prod
    environment:
      - discovery.type=single-node
    volumes:
      - type: volume
        source: es_data
        target: /usr/share/elasticsearch/data

volumes:
  es_data:
  postgres_data:
  redis_data:
  static_volume:
  media_volume: