version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: django
    volumes:
      - type: volume
        source: static_volume
        target: /home/app/web/staticfiles
    command: gunicorn webapp.wsgi:application -b 0.0.0.0:8000
    expose:
      - 8000
    env_file:
      - code/env_var/.env.app
    depends_on:
      - postgres
      - redis
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx
    volumes:
      - type: volume
        source: static_volume
        target: /home/app/web/staticfiles
    depends_on:
      - web
    ports:
      - "8000:80"
  postgres:
    image: postgres:13.0-alpine
    container_name: postgres
    volumes:
      - type: volume
        source: postgres_data
        target: /var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin_pass
      - POSTGRES_DB=prod_db
  redis:
    image: redis:alpine
    container_name: redis
volumes:
  postgres_data:
  static_volume:
